# Generated by Django 4.0.2 on 2022-02-17 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('address', models.TextField(verbose_name='Address')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Mailing list',
                'verbose_name_plural': 'Mailing lists',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('image', models.ImageField(upload_to='product-images/', verbose_name='Image')),
                ('brand', models.CharField(max_length=255, null=True, verbose_name='Brand')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time Create')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time Update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Gadget',
                'verbose_name_plural': 'Gadgets',
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='MenClothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=50, verbose_name='Size')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': "Men's Clothes",
                'verbose_name_plural': "Men's Clothes",
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='WomenClothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.product')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=50, verbose_name='Size')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': "Women's Clothes",
                'verbose_name_plural': "Women's Clothes",
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images/', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
