# Generated by Django 4.0.1 on 2022-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_views',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Count Views'),
        ),
    ]
