# Generated by Django 4.0.1 on 2022-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_count_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subject', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subject')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
