# Generated by Django 4.0.1 on 2022-02-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_products', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во товаров в корзине')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость корзины')),
                ('status', models.CharField(choices=[('new', 'Новая корзина'), ('in_process', 'В состоянии выбора'), ('in_order', 'В заказе')], default='Новая корзина', max_length=20, verbose_name='Статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveSmallIntegerField()),
                ('product_name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('total_products', models.PositiveSmallIntegerField(verbose_name='Общее кол-во товаров')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая стоимость')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carts', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Продукт в Корзине',
                'verbose_name_plural': 'Продукты в Корзине',
            },
        ),
    ]
