# Generated by Django 4.0.1 on 2022-02-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproducts',
            options={'verbose_name': 'Product on Cart', 'verbose_name_plural': 'Products on Cart'},
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carts', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='total_products',
            field=models.PositiveSmallIntegerField(verbose_name='Total Products'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='final_products',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Final Products'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('new', 'New Cart'), ('in_process', 'In Process'), ('in_order', 'In Order')], default='New Cart', max_length=20, verbose_name='Status'),
        ),
    ]
