# Generated by Django 4.0.1 on 2022-02-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cartproducts_options_alter_carts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='total_products',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Products'),
        ),
    ]
