# Generated by Django 4.0.1 on 2022-02-20 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0003_alter_cartproducts_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('deliver_type', models.CharField(choices=[('deliver', 'Deliver'), ('self', 'Self')], default='Доставка', max_length=10, verbose_name='Deliver Type')),
                ('status', models.CharField(choices=[('new', 'New Order'), ('in_deliver', 'In deliver'), ('completed', 'Completed'), ('denied', 'Denied')], default='New Order', max_length=12, verbose_name='Status')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.carts', verbose_name='Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
